services:
  mongodb:
    image: "mongo:7-jammy"
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/db:/data/db
    restart: unless-stopped
    networks:
      - internal-services

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - ${APP_DATA_DIR}/data/elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: unless-stopped
    networks:
      - internal-services

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ${APP_DATA_DIR}/data/files:/data
    restart: unless-stopped
    networks:
      - internal-services

  rekoni:
    image: hardcoreeng/rekoni-service:v0.6.313
    environment:
      - SECRET=secret
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks:
      - internal-services
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.huly-rekoni-web-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.huli-rekoni-stripprefix.stripprefix.prefixes=/rekoni"

      traefik.http.services.huly-rekoni.loadbalancer.server.port: 4004
      # Web
      traefik.http.routers.huly-rekoni-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/rekoni`)
      traefik.http.routers.huly-rekoni-insecure.entrypoints: web
      traefik.http.routers.huly-rekoni-insecure.service: huly-rekoni
      traefik.http.routers.huly-rekoni-insecure.middlewares: huly-rekoni-web-redirect
      # Websecure
      traefik.http.routers.huly-rekoni.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/rekoni`)
      traefik.http.routers.huly-rekoni.entrypoints: websecure
      traefik.http.routers.huly-rekoni.service: huly-rekoni
      traefik.http.routers.huly-rekoni.middlewares: huly-rekoni-stripprefix
      traefik.http.routers.huly-rekoni.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.huly-rekoni-local-insecure.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/rekoni`)
      traefik.http.routers.huly-rekoni-local-insecure.entrypoints: web
      traefik.http.routers.huly-rekoni-local-insecure.service: huly-rekoni
      traefik.http.routers.huly-rekoni-local-insecure.middlewares: huly-rekoni-web-redirect
      # Local domain secure
      traefik.http.routers.huly-rekoni-local.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/rekoni`)
      traefik.http.routers.huly-rekoni-local.entrypoints: websecure
      traefik.http.routers.huly-rekoni-local.service: huly-rekoni
      traefik.http.routers.huly-rekoni.middlewares: huly-rekoni-stripprefix
      traefik.http.routers.huly-rekoni-local.tls: true

      # - "traefik.enable=true"
      # - "traefik.http.routers.rekoni.entrypoints=websecure"
      # - "traefik.http.services.rekoni.loadbalancer.server.port=4004"
      # - "traefik.http.routers.rekoni.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/rekoni`)"
      # - "traefik.http.routers.rekoni.middlewares=rekoni-stripprefix"
      # - "traefik.http.middlewares.rekoni-stripprefix.stripprefix.prefixes=/rekoni"
      # - "traefik.http.routers.rekoni.tls=true"
      # - "traefik.http.routers.rekoni.tls.certresolver=myresolver"

  transactor:
    image: hardcoreeng/transactor:v0.6.313
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=secret
      - SERVER_CURSOR_MAXTIMEMS=30000
      - ELASTIC_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - MONGO_URL=mongodb://mongodb:27017
      - METRICS_CONSOLE=false
      - METRICS_FILE=metrics.txt
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - FRONT_URL=http://localhost:8087
      - ACCOUNTS_URL=http://account:3000
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - internal-services
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.huly-transactor-web-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.huly-transactor-stripprefix.stripprefix.prefixes=/transactor"
      traefik.http.services.huly-transactor.loadbalancer.server.port: 3333
      # Web
      traefik.http.routers.huly-transactor-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/transactor`)
      traefik.http.routers.huly-transactor-insecure.entrypoints: web
      traefik.http.routers.huly-transactor-insecure.service: huly-transactor
      traefik.http.routers.huly-transactor-insecure.middlewares: huly-transactor-web-redirect
      # Websecure
      traefik.http.routers.huly-transactor.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.huly-transactor.entrypoints: websecure
      traefik.http.routers.huly-transactor.service: huly-transactor
      traefik.http.routers.huly-transactor.middlewares: huly-transactor-stripprefix
      traefik.http.routers.huly-transactor.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.huly-transactor-local-insecure.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/transactor`)
      traefik.http.routers.huly-transactor-local-insecure.entrypoints: web
      traefik.http.routers.huly-transactor-local-insecure.service: huly-transactor
      traefik.http.routers.huly-transactor-local-insecure.middlewares: huly-transactor-web-redirect
      # Local domain secure
      traefik.http.routers.huly-transactor-local.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/transactor`)
      traefik.http.routers.huly-transactor-local.entrypoints: websecure
      traefik.http.routers.huly-transactor-local.service: huly-transactor
      traefik.http.routers.huly-transactor-local.middlewares: huly-transactor-stripprefix
      traefik.http.routers.huly-transactor-local.tls: true

      # - "traefik.enable=true"
      # - "traefik.http.routers.transactor.entrypoints=transactor"
      # - "traefik.http.routers.transactor.rule=Host(`${APP_DOMAIN}`)"
      # - "traefik.http.services.transactor.loadbalancer.server.port=3333"
      # - "traefik.http.routers.transactor.tls=true"
      # - "traefik.http.routers.transactor.tls.certresolver=myresolver"

  collaborator:
    image: hardcoreeng/collaborator:v0.6.313
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=secret
      - ACCOUNTS_URL=http://account:3000
      - MONGO_URL=mongodb://mongodb:27017
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped
    networks:
      - internal-services
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.huly-collaborator-web-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.huly-collaborator-stripprefix.stripprefix.prefixes=/collaborator"
      traefik.http.services.huly-collaborator.loadbalancer.server.port: 3078
      # Web
      traefik.http.routers.huly-collaborator-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/collaborator`)
      traefik.http.routers.huly-collaborator-insecure.entrypoints: web
      traefik.http.routers.huly-collaborator-insecure.service: huly-collaborator
      traefik.http.routers.huly-collaborator-insecure.middlewares: huly-collaborator-web-redirect
      # Websecure
      traefik.http.routers.huly-collaborator.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/collaborator`)
      traefik.http.routers.huly-collaborator.entrypoints: websecure
      traefik.http.routers.huly-collaborator.service: huly-collaborator
      traefik.http.routers.huly-collaborator.middlewares: huly-collaborator-stripprefix
      traefik.http.routers.huly-collaborator.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.huly-collaborator-local-insecure.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/collaborator`)
      traefik.http.routers.huly-collaborator-local-insecure.entrypoints: web
      traefik.http.routers.huly-collaborator-local-insecure.service: huly-collaborator
      traefik.http.routers.huly-collaborator-local-insecure.middlewares: huly-collaborator-web-redirect
      # Local domain secure
      traefik.http.routers.huly-collaborator-local.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/collaborator`)
      traefik.http.routers.huly-collaborator-local.entrypoints: websecure
      traefik.http.routers.huly-collaborator-local.service: huly-collaborator
      traefik.http.routers.huly-collaborator-local.middlewares: huly-collaborator-stripprefix
      traefik.http.routers.huly-collaborator-local.tls: true

  account:
    image: hardcoreeng/account:v0.6.313
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=secret
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333/transactor;ws://${APP_DOMAIN}/transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://front:8080
      - INIT_WORKSPACE=demo-tracker
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://localhost:3000
      - ACCOUNT_PORT=3000
    restart: unless-stopped
    networks:
      - internal-services
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.huly-account-web-redirect.redirectscheme.scheme: https
      traefik.http.middlewares.huly-account-stripprefix.stripprefix.prefixes=/accounts"

      traefik.http.services.huly-account.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.huly-account-insecure.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/accounts`)
      traefik.http.routers.huly-account-insecure.entrypoints: web
      traefik.http.routers.huly-account-insecure.service: huly-account
      traefik.http.routers.huly-account-insecure.middlewares: huly-account-web-redirect

      # Websecure
      traefik.http.routers.huly-account.rule: Host(`${APP_DOMAIN}`) && PathPrefix(`/accounts`)
      traefik.http.routers.huly-account.entrypoints: websecure
      traefik.http.routers.huly-account.service: huly-account
      traefik.http.routers.huly-account-insecure.middlewares: huly-account-stripprefix

      traefik.http.routers.huly-account.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.huly-account-local-insecure.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/accounts`)
      traefik.http.routers.huly-account-local-insecure.entrypoints: web
      traefik.http.routers.huly-account-local-insecure.service: huly-account
      traefik.http.routers.huly-account-local-insecure.middlewares: huly-account-web-redirect
      # Local domain secure
      traefik.http.routers.huly-account-local.rule: Host(`huly.${LOCAL_DOMAIN}`) && PathPrefix(`/accounts`)
      traefik.http.routers.huly-account-local.entrypoints: websecure
      traefik.http.routers.huly-account-local.service: huly-account
      traefik.http.routers.huly-account-local.middlewares: huly-account-stripprefix
      traefik.http.routers.huly-account-local.tls: true
  workspace:
    image: hardcoreeng/workspace:v0.6.313
    environment:
      - SERVER_SECRET=secret
      - MONGO_URL=mongodb://mongodb:27017
      - TRANSACTOR_URL=ws://transactor:3333/transactor;wss://${APP_DOMAIN}:3333/transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - NOTIFY_INBOX_ONLY=true
    restart: unless-stopped
    networks:
      - internal-services

  front:
    image: hardcoreeng/front:v0.6.313
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=secret
      - ACCOUNTS_URL=https://${APP_DOMAIN}/accounts
      - REKONI_URL=https://${APP_DOMAIN}/rekoni
      - CALENDAR_URL=https://${APP_DOMAIN}:8095
      - GMAIL_URL=https://${APP_DOMAIN}:8088
      - TELEGRAM_URL=https://${APP_DOMAIN}:8086
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=wss://${APP_DOMAIN}/collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MONGO_URL=mongodb://mongodb:27017
      - TITLE=Huly Self Host
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
    restart: unless-stopped
    networks:
      - internal-services
      - tipi_main_network
    labels:
      traefik.enable: true
      traefik.http.middlewares.huly-front-web-redirect.redirectscheme.scheme: https
      traefik.http.services.huly-front.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.huly-front-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.huly-front-insecure.entrypoints: web
      traefik.http.routers.huly-front-insecure.service: huly-front
      traefik.http.routers.huly-front-insecure.middlewares: huly-front-web-redirect
      # Websecure
      traefik.http.routers.huly-front.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.huly-front.entrypoints: websecure
      traefik.http.routers.huly-front.service: huly-front
      traefik.http.routers.huly-front.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.huly-front-local-insecure.rule: Host(`huly-front.${LOCAL_DOMAIN}`)
      traefik.http.routers.huly-front-local-insecure.entrypoints: web
      traefik.http.routers.huly-front-local-insecure.service: huly-front
      traefik.http.routers.huly-front-local-insecure.middlewares: huly-front-web-redirect
      # Local domain secure
      traefik.http.routers.huly-front-local.rule: Host(`huly-front.${LOCAL_DOMAIN}`)
      traefik.http.routers.huly-front-local.entrypoints: websecure
      traefik.http.routers.huly-front-local.service: huly-front
      traefik.http.routers.huly-front-local.tls: true

networks:
  internal-services:
    name: internal-services
